<?php
// Do not edit this file directly! It is automatically generated after every container start.
class DATABASE_CONFIG {
    public $default = [
        'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => '{{ MYSQL_HOST }}',
        'port' => {{ MYSQL_PORT }},
        'login' => '{{ MISP_DB_USER }}',
        'password' => {{ MISP_DB_PASSWORD | str }},
        'database' => '{{ MISP_DB }}',
        'prefix' => '',
        'encoding' => 'utf8',
        'settings' => ['time_zone' => '"+00:00"'],
    ];
}
